name: TEST
on:
  # workflow_dispatch allow us o manually trigger 
  workflow_dispatch:

env:
  SERVER: 'devops.mysql.database.azure.com'
  DBUSER: 'devops'
  DBPASSWORD: 'Ryder@123azure'
  DBNAME: 'devops'
  
jobs:
  job1:
    runs-on: windows-latest
    steps:
      - uses: ggsoftcompany/whiplash-reviewapp-composite-action/single-action@main
        with:
          api-key: 'ak'
          pipeline-name: 'pepe'
          app-name-prefix: 'wl-core'
          github-access-key: '2'
          secondary-app-name-prefix: 'wl-ui'
          
          
          
