name: TEST
on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, closed]
  # workflow_dispatch allow us o manually trigger 
  workflow_dispatch:

env:
  HEROKU_PIPELINE: 'ggsoft-backend-pipeline'
  APP_PREFIX: 'ggsoft-backend-ra'
  SECONDARY_HEROKU_PIPELINE: 'ggsoft-ui-pipeline'
  SECONDARY_APP_PREFIX: 'ggsoft-ui-ra'
  SECONDARY_APP_RESPOSITORY: 'ggsoftcompany/node-js-getting-started-ui'
  SECONDARY_APP_SOURCE_BRANCH: 'main'
  
jobs:
  job1:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Deploy Heroku Review App  
        uses: ggsoftcompany/whiplash-reviewapp-composite-action/single-action@main
        with:
          api-key: '${{secrets.herokuApiKey}}'
          pipeline-name: '${{env.HEROKU_PIPELINE}}'
          app-name-prefix: '${{env.APP_PREFIX}}'
          github-access-key: ${{secrets.githubAccessToken}}
          secondary-app-pipeline-name: '${{env.SECONDARY_HEROKU_PIPELINE}}'
          secondary-app-name-prefix: '${{env.SECONDARY_APP_PREFIX}}'
          secondary-app-repository: '${{env.SECONDARY_APP_RESPOSITORY}}'
          secondary-app-source-branch: '${{env.SECONDARY_APP_SOURCE_BRANCH}}'
          
          
          
