name: TEST
on:
  # workflow_dispatch allow us o manually trigger 
  workflow_dispatch:

env:
  SERVER: 'devops.mysql.database.azure.com'
  DBUSER: 'devops'
  DBPASSWORD: 'Ryder@123azure'
  DBNAME: 'devops'
  
jobs:
  job1:
    runs-on: windows-latest
    steps:
      - run: choco install mysql.odbc
      - id: aa
        shell: powershell
        run: |
          Add-Type -Path "./MySql.Data.dll"
          Write-Output "Establishing a connection with the target server ${{env.SERVER}} ..."
          $connection = [MySql.Data.MySqlClient.MySqlConnection]@{ConnectionString="server=$server;uid=${{env.DBUSER}};pwd=${{env.DBPASSWORD}};database=${{env.DBNAME}};SslMode=none;"}
          $connection.Open()
          Write-Output "Connection successfully."
