name: AUTOMATE-REVIEW
on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, closed]
  # workflow_dispatch allow us o manually trigger 
  workflow_dispatch:

env:
  HEROKU_PIPELINE: 'ggsoft-backend-pipeline'
  APP_PREFIX: 'ggsoft-backend-ra'
  SECONDARY_HEROKU_PIPELINE: 'ggsoft-ui-pipeline'
  SECONDARY_APP_PREFIX: 'ggsoft-ui-ra'
  SECONDARY_APP_RESPOSITORY: 'ggsoftcompany/node-js-getting-started-ui'
  SECONDARY_APP_SOURCE_BRANCH: 'main'
  
jobs:
  automate-review-app:
    name: 'Deploy Review APP for Whiplash Core'
    runs-on: windows-latest
    environment: 
      name: 'Review App'
      url: '${{steps.deploy.outputs.app-url}}'
    steps:
      - id: deploy
        uses: ggsoftcompany/whiplash-reviewapp-composite-action/single-action@main
        with:
          api-key: '${{secrets.herokuApiKey}}'
          pipeline-name: '${{env.HEROKU_PIPELINE}}'
          app-name-prefix: '${{env.APP_PREFIX}}'
          github-access-key: ${{secrets.githubAccessToken}}
          secondary-app-pipeline-name: '${{env.SECONDARY_HEROKU_PIPELINE}}'
          secondary-app-name-prefix: '${{env.SECONDARY_APP_PREFIX}}'
          secondary-app-repository: '${{env.SECONDARY_APP_RESPOSITORY}}'
          secondary-app-source-branch: '${{env.SECONDARY_APP_SOURCE_BRANCH}}'
      
      - name: Show review app urls 
        run: |
          echo "Review App URL: ${{ steps.deploy.outputs.app-url }}"
          echo "Secondary Review App URL: ${{ steps.deploy.outputs.secondary-app-url }}"
      
      - name: Create comment on commit  
        uses: phulsechinmay/rewritable-pr-comment@v0.2.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMENT_IDENTIFIER: "review-app-deployed"
          message: |
            A new review app was deployed to try out this pull request.
                                          
                              👇🏽

            Primary App: ${{ steps.deploy.outputs.app-url }}
            Secondary App: ${{ steps.deploy.outputs.secondary-app-url }}
