name: TEST
on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]
  # workflow_dispatch allow us o manually trigger 
  workflow_dispatch:

env:
  HEROKU_PIPELINE: 'ggsoft-ui-pipeline'
  APP_PREFIX: 'ggsoft-backend-ra'
  SECONDARY_APP_PREFIX: 'ggsoft-ui-ra'
  
jobs:
  job1:
    runs-on: windows-latest
    steps:
      - uses: ggsoftcompany/whiplash-reviewapp-composite-action/single-action@main
        with:
          api-key: '${{secrets.herokuApiKey}}'
          pipeline-name: '${{env.HEROKU_PIPELINE}}'
          app-name-prefix: '${{env.APP_PREFIX}}'
          github-access-key: ${{secrets.githubAccessToken}}
          secondary-app-name-prefix: '${{env.SECONDARY_APP_PREFIX}}'
          
          
          
