name: REVIEW-APP-CD
on:
  # trigger every time a pull request to main branch is opened, reopened or labeled.
  # Used to spin up a review app
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, labeled]
  # workflow_dispatch allow us o manually trigger
  workflow_dispatch:
env:
  PRIMARY_HEROKU_PIPELINE: 'ggsoft-backend-pipeline'
  PRIMARY_REVIEWAPP_PREFIX_URL: 'ggsoft-backend-ra'
jobs:
  
  Pre-execution:
    #if: ${{github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'review-app')}}
    runs-on: windows-latest
    # Map a step output to a job output
    outputs:
      reviewapp_URL: ${{ steps.create-review-apps-url.outputs.reviewapp_URL }}
      secondaryReviewapp_URL: ${{ steps.create-review-apps-url.outputs.secondaryReviewapp_URL }}
    steps:
      - id: create-review-apps-url
        run: |
          $reviewAppURL = "https://${{env.PRIMARY_REVIEWAPP_PREFIX_URL}}-pr-${{github.event.pull_request.number}}.herokuapp.com"
          echo "reviewapp_URL=$($reviewAppURL)"
        shell: powershell
  
  #Primary-Review-App:
  #  
  #  # The type of runner that the job will run on
  #  runs-on: windows-latest
  #  env:
  #    REVIEWAPP_PREFIX_URL: 'ggsoft-backend-ra'
  #    SECONDARY_REVIEWAPP_PREFIX_URL: 'ggsoft-ui-ra'
  #    SECONDARY_REVIEWAPP_NEW_BRANCH_PREFIX: 'forbackendpr'
  #  steps:
  #    - uses: ggsoftcompany/whiplash-reviewapp-composite-action@main
  #      with:
  #        github_accessToken: ${{secrets.githubAccessToken}}
  #        heroku_apiKey: ${{secrets.herokuApiKey}}
  #        heroku_pipelineName: '${{env.PRIMARY_HEROKU_PIPELINE}}'
  #        reviewapp_prefixURL: '${{env.REVIEWAPP_PREFIX_URL}}'
  #        secondaryReviewapp_prefixURL: '${{env.SECONDARY_REVIEWAPP_PREFIX_URL}}'
  #        secondaryReviewapp_newBranchPrefix: '${{env.SECONDARY_REVIEWAPP_NEW_BRANCH_PREFIX}}'
  #  
  #Secondary-Review-App:
  #  if: ${{github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'review-app')}}
  #  # The type of runner that the job will run on
  #  runs-on: windows-latest
  #  env:
  #    REVIEWAPP_PREFIX_URL: 'ggsoft-backend-ra'
  #    SECONDARY_REVIEWAPP_PREFIX_URL: 'ggsoft-ui-ra'
  #    SECONDARY_REVIEWAPP_NEW_BRANCH_PREFIX: 'forbackendpr'
  #  steps:
  #    - uses: ggsoftcompany/whiplash-reviewapp-composite-action@main
  #      with:
  #        github_accessToken: ${{secrets.githubAccessToken}}
  #        heroku_apiKey: ${{secrets.herokuApiKey}}
  #        heroku_pipelineName: '${{env.PRIMARY_HEROKU_PIPELINE}}'
  #        reviewapp_prefixURL: '${{env.REVIEWAPP_PREFIX_URL}}'
  #        secondaryReviewapp_prefixURL: '${{env.SECONDARY_REVIEWAPP_PREFIX_URL}}'
  #        secondaryReviewapp_newBranchPrefix: '${{env.SECONDARY_REVIEWAPP_NEW_BRANCH_PREFIX}}'
