name: WHIPLASH-CORE-WORKFLOW

# Controls when the workflow will run
on:
  # trigger every time a pull request to main branch is opened, reopened or labeled.
  # Used to spin up a review app
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, labeled]
  
  # trigger every time a new push to the main branch. deploy to development environment
  # trigger every time a new push to qa branch. deploy to QA
  # trigger every time a new push to stg branch. deploy to Staging
  # trigger every time a new push to any release branch. deploy to Production
  push:
    branches: 
      - main
      - qa
      - stg
      - 'releases/**'
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PRIMARY_HEROKU_PIPELINE: 'ggsoft-backend-pipeline'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ReviewApp:
    if: ${{github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'review-app')}}
    # The type of runner that the job will run on
    runs-on: windows-latest
    env:
      REVIEWAPP_PREFIX_URL: 'ggsoft-backend-ra'
      SECONDARY_REVIEWAPP_PREFIX_URL: 'ggsoft-ui-ra'
      SECONDARY_REVIEWAPP_NEW_BRANCH_PREFIX: 'forbackendpr'
    steps:
      - uses: ggsoftcompany/whiplash-reviewapp-composite-action@main
        with:
          github_accessToken: ${{secrets.githubAccessToken}}
          heroku_apiKey: ${{secrets.herokuApiKey}}
          heroku_pipelineName: '${{env.PRIMARY_HEROKU_PIPELINE}}'
          reviewapp_prefixURL: '${{env.REVIEWAPP_PREFIX_URL}}'
          secondaryReviewapp_prefixURL: '${{env.SECONDARY_REVIEWAPP_PREFIX_URL}}'
          secondaryReviewapp_newBranchPrefix: '${{env.SECONDARY_REVIEWAPP_NEW_BRANCH_PREFIX}}'
      
  Development:  
    if: ${{github.event_name == 'push' && github.ref_name == 'main'}}
    runs-on: windows-latest
    steps:
     - run: |
          write-output: "Deploy to DEvelopment"
